export const GET_REWARDS_RESPONSE = 'GET_REWARDS_RESPONSE';
export const GET_REWARD_RESPONSE = 'GET_REWARD_RESPONSE';
export const ADD_NEW_REWARD_RESPONSE = 'ADD_NEW_REWARD_RESPONSE';
export const UPDATE_EXISTING_REWARD_RESPONSE = 'UPDATE_EXISTING_REWARD_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
